#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kdenlive contributors
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
"""Generate the KDE color schemes from the design tokens.

The color schemes drive every widget the Kdenlive style does not paint itself, and the
semantic colors KColorScheme hands out. Generating them from tokens.json keeps them in
step with the design system. Run after editing tokens.json:

    python3 src/design/generate-color-schemes.py
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent.parent / "data" / "color-schemes"

# KColorScheme color set -> (background, alternate background) tokens
BACKGROUNDS = {
    "Window": ("surface-panel", "surface-sidebar"),
    "View": ("surface-window", "surface-panel"),
    "Button": ("surface-control", "surface-control-hover"),
    "Header": ("surface-window", "surface-sidebar"),
    "Tooltip": ("surface-raised", "surface-panel"),
    "Complementary": ("surface-viewer", "surface-timeline"),
    "Selection": ("accent-fill", "accent"),
}

# Foreground roles shared by every set but Selection
FOREGROUNDS = {
    "ForegroundNormal": "ink",
    "ForegroundInactive": "ink-secondary",
    "ForegroundActive": "accent",
    "ForegroundLink": "accent",
    "ForegroundVisited": "role-titles",
    "ForegroundNegative": "danger",
    "ForegroundNeutral": "warning",
    "ForegroundPositive": "success",
    "DecorationFocus": "focus-ring",
    "DecorationHover": "accent",
}

THEMES = {"dark": "KdenliveDark", "light": "KdenliveLight"}
NAMES = {"dark": "Kdenlive Dark", "light": "Kdenlive Light"}


def load_tokens():
    tokens = json.loads((HERE / "tokens.json").read_text())
    first = tokens["color"]["themes"][0]["id"]
    raw = {}
    for token in tokens["color"]["tokens"]:
        value = token["value"]
        raw[token["name"]] = value if isinstance(value, dict) else {first: value}
    return raw, first


def resolve(raw, first, name, theme, depth=0):
    value = raw[name].get(theme, raw[name][first])
    if value.startswith("{"):
        if depth > 16:
            raise ValueError(f"alias cycle at {name}")
        return resolve(raw, first, value[1:-1], theme, depth + 1)
    return value


def rgb(hex_color):
    """KDE color schemes take opaque r,g,b"""
    value = hex_color.lstrip("#")[:6]
    return ",".join(str(int(value[i:i + 2], 16)) for i in (0, 2, 4))


def scheme(raw, first, theme):
    color = lambda name: rgb(resolve(raw, first, name, theme))
    lines = [
        "# SPDX-FileCopyrightText: 2026 Kdenlive contributors",
        "# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL",
        "# Generated by src/design/generate-color-schemes.py from src/design/tokens.json. Do not edit.",
        "",
        "[ColorEffects:Disabled]",
        "Color=56,56,56", "ColorAmount=0", "ColorEffect=0", "ContrastAmount=0.65", "ContrastEffect=1",
        "IntensityAmount=0.1", "IntensityEffect=2",
        "",
        "[ColorEffects:Inactive]",
        "ChangeSelectionColor=true", "Color=112,111,110", "ColorAmount=0.025", "ColorEffect=2",
        "ContrastAmount=0.1", "ContrastEffect=2", "Enable=false", "IntensityAmount=0", "IntensityEffect=0",
        "",
    ]
    for color_set, (background, alternate) in BACKGROUNDS.items():
        for section in ([f"[Colors:{color_set}]"] + ([f"[Colors:{color_set}][Inactive]"] if color_set == "Header" else [])):
            lines.append(section)
            lines.append(f"BackgroundAlternate={color(alternate)}")
            lines.append(f"BackgroundNormal={color(background)}")
            for role, token in FOREGROUNDS.items():
                if color_set == "Selection" and role.startswith("Foreground"):
                    token = "on-accent" if role in ("ForegroundNormal", "ForegroundActive", "ForegroundLink") else token
                lines.append(f"{role}={color(token)}")
            lines.append("")
    lines += [
        "[General]",
        f"ColorScheme={THEMES[theme]}",
        f"Name={NAMES[theme]}",
        "shadeSortColumn=true",
        "",
        "[KDE]",
        "contrast=4",
        "",
        "[WM]",
        f"activeBackground={color('surface-window')}",
        f"activeBlend={color('ink')}",
        f"activeForeground={color('ink')}",
        f"inactiveBackground={color('surface-window')}",
        f"inactiveBlend={color('ink-secondary')}",
        f"inactiveForeground={color('ink-secondary')}",
        "",
    ]
    return "\n".join(lines)


def main():
    raw, first = load_tokens()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for theme, file_name in THEMES.items():
        (OUTPUT / f"{file_name}.colors").write_text(scheme(raw, first, theme))
        print(f"wrote {file_name}.colors")


if __name__ == "__main__":
    main()
